LAB_DESCRIPTION="Laboratorio introduttivo Kathara: Due PC e un Router"
LAB_VERSION=1.0
LAB_AUTHOR="Reti di Calcolatori"

# pc1 è collegato al dominio di collisione A (LAN 1)
pc1[0]="A"

# router ha due interfacce: eth0 sul dominio A e eth1 sul dominio B
router[0]="A"
router[1]="B"

# pc2 è collegato al dominio di collisione B (LAN 2)
pc2[0]="B"
